### PR TITLE
Fix merge problems in src/utils/merge.ts

### PR DESCRIPTION
**Pull request by pcdummy**
By adding a source.hasOwnProperty(key) check.

### CODE REVIEW

**Comment by SoEasy** [comment]
Hello! Thank you for request! But I have no idea for what you need check own property :)
Can you show example which demonstrate incorrect behavior without your fix?

**Comment by pcdummy** [comment]
In [this example](https://git.webmeisterei.com/minadmin/js-oidc/blob/0.0.1/src/lib/flow.service.ts) you can see that i add some methods and variables to the class, it won't work without this fix.

**Comment by pcdummy** [comment]
@SoEasy any news?

**Comment by SoEasy** [comment]
Hello! Today or tomorrow I will merge and up version

**Pull request merged**
